# Generated by Django 2.2.3 on 2019-07-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('arval_date', models.CharField(default=None, max_length=40)),
                ('dep_date', models.CharField(default=None, max_length=40)),
                ('persons', models.CharField(default=None, max_length=40)),
                ('child', models.CharField(default=None, max_length=40)),
                ('room_type', models.CharField(default=None, max_length=40)),
                ('total_rooms', models.IntegerField(default=0)),
                ('customer_name', models.CharField(default=None, max_length=40)),
            ],
        ),
    ]
